# port that will receive http requests.
# some operating systems will requires a admin role to use ports < 1024
port: 9082

# index [optional, default value: False]
# is an index page required (in case a visitors send a request to the server using an unknown hostname
# default: False
index: True
    
sites:
  - ref: gaetanasolwedding              		# the name of the website on Google Sites
  
    host: gaetanasolwedding.com         		# the vhost linked with the current site
    language: en-US, en;q=0.9           		# a language hint, to get a properly localized page
    description: Xavier and Elisa's wedding  	# a short description of this site
    faviconpath: favicon.ico					# specify a path to an icon file
    
#Proxy
    frontproxy:
    type: CloudFlare
    force-ssl: True
